name: "Build ESP-IDF Projects"
description: "Build ESP-IDF projects"

inputs:
  paths:
    description: space-separated paths to the esp-idf project
    default: .
  target:
    description: target to build
    default: all
  parallel_index:
    description: 1-based index of the parallel job
    default: "1"
  parallel_count:
    description: total number of parallel jobs
    default: "1"
  idf_path:
    description: path to the ESP-IDF
    default: /opt/esp/idf
  modified_files:
    description: "[FOR INTERNAL TEST] semicolon-separated list of modified files. By default get from PR"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Get changed files
      id: changed-files
      if: ${{ !inputs.modified_files }}
      uses: tj-actions/changed-files@v45
    - name: Install Dependencies
      shell: bash
      run: |
        . ${{ inputs.idf_path }}/export.sh
        pip install -U idf-ci
    - name: Build ESP-IDF Projects
      shell: bash
      run: |
        . ${{ inputs.idf_path }}/export.sh
        idf-ci build run \
          --paths ${{ inputs.paths }} \
          --target ${{ inputs.target }} \
          --parallel-index ${{ inputs.parallel_index }} \
          --parallel-count ${{ inputs.parallel_count }} \
          --modified-files "${{ inputs.modified_files || steps.changed-files.outputs.all_changed_files }}"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app_binaries_${{ inputs.parallel_index }}
        path: |
          **/build_*_*/bootloader/bootloader.bin
          **/build_*_*/partition_table/partition-table.bin
          **/build_*_*/*.bin
          **/build_*_*/flasher_args.json
          **/build_*_*/config/sdkconfig.json
          **/build_*_*/size.json
          **/build_*_*/build.log
          app_info_*.txt
          build_summary_*.xml
          size_info_*.txt
